##
# Unit Test config overrides
##

include "application.conf"

# Overrides application.conf setting - ephemeral per-test database instance (no data/db persists across spec tests)
slick.dbs.default.db.url = "jdbc:h2:mem:;MODE=PostgreSQL;DATABASE_TO_LOWER=true"